function addpath_MDCKtools()
        
        thisdir = fileparts( mfilename( 'fullpath' ) );
        addpath( thisdir,...
                [thisdir filesep 'Classes'],...
                [thisdir filesep 'HelperFunctions'],...                
                [thisdir filesep 'InternalHelperFunctions'],...                
                [thisdir filesep 'InternalHelperFunctions' filesep 'RawDataFunctions'],...                
                [thisdir filesep 'HelperFunctions' filesep 'xml_io_tools'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout' filesep 'Patch'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout' filesep 'layoutHelp'],...                
                [thisdir filesep 'OMEROMatlab'],...                                
                [thisdir filesep 'BFMatlab'],...                                
                [thisdir filesep 'GUIDEInterfaces'],...                                
                [thisdir filesep 'OMEROUtilities'],...                                                
                [thisdir filesep 'OMEuiUtils'],...                                                            
                [thisdir filesep 'SegmentationFunctions'],...
                [thisdir filesep 'SegmentationFunctions' filesep 'Support'],...
                [thisdir filesep 'Diffusion'],...
                [matlabroot filesep 'toolbox' filesep 'images' filesep 'images']);            
                
            addpath( ...
                [thisdir filesep 'ICY_Matlab' filesep 'matlabcommunicator'],... 
                [thisdir filesep 'ICY_Matlab' filesep 'matlabxserver']);                                                
            
end